# Generated by Django 4.1 on 2022-08-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllStories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("by", models.CharField(max_length=100)),
                ("time", models.DateTimeField()),
                ("url", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("score", models.BigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "All Story",
                "verbose_name_plural": "All Stories",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("newsapp.allstories",),
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("newsapp.allstories",),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("newsapp.allstories",),
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "allstories_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="newsapp.allstories",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polloptions_poll",
                        to="newsapp.poll",
                    ),
                ),
            ],
            bases=("newsapp.allstories",),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "allstories_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="newsapp.allstories",
                    ),
                ),
                (
                    "kids",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_comments",
                        to="newsapp.comment",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_story",
                        to="newsapp.story",
                    ),
                ),
            ],
            bases=("newsapp.allstories",),
        ),
    ]
