# Generated by Django 4.1 on 2022-08-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allstories",
            options={
                "ordering": ["-time", "text"],
                "verbose_name": "All Story",
                "verbose_name_plural": "All Stories",
            },
        ),
    ]
