# Generated by Django 4.1 on 2022-08-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0002_alter_allstories_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allstories",
            options={
                "ordering": ["-time", "title"],
                "verbose_name": "All Story",
                "verbose_name_plural": "All Stories",
            },
        ),
        migrations.AlterModelOptions(
            name="poll",
            options={"ordering": ["-time", "title"]},
        ),
        migrations.AlterModelOptions(
            name="story",
            options={
                "ordering": ["-time", "title"],
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
            },
        ),
    ]
