# Generated by Django 4.1 on 2022-08-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0002_alter_comment_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allstories",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
